---
sudo: required
dist: trusty

language: generic

env:
  - ANSIBLE_VERSION="1.9" DB_NAME=""
  - ANSIBLE_VERSION="2.0" DB_NAME=""
  - ANSIBLE_VERSION="1.9" DB_NAME=test_db
  - ANSIBLE_VERSION="2.0" DB_NAME=test_db

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq python-apt python-pycurl
install:
  - sudo pip install "ansible~=$ANSIBLE_VERSION"
  - sudo ansible-galaxy install bbatsche.MySQL-Install
script:
  - echo localhost > inventory

  # Syntax check
  - ansible-playbook -i inventory travis-playbook.yml --syntax-check

  # Play test
  - ansible-playbook -i inventory travis-playbook.yml --connection=local -e "db_name=$DB_NAME"

  # Idempotence test
  - >
    ansible-playbook -i inventory travis-playbook.yml --connection=local -e "db_name=$DB_NAME"
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)

notifications:
    webhooks: https://galaxy.ansible.com/api/v1/notifications/
